#!/usr/bin/env python3
"""
Streaming Ingestion -- producer.py: synthetic events -> Kinesis Data Stream

Simulates an external system publishing new literacy indicator measurements
in near-real time. Since SAEB/INEP doesn't expose a streaming API, this
script generates plausible synthetic events:

  - Draws real municipalities (municipality_id + state_code) from the
    municipalities CSV in raw_downloads/, if available (otherwise falls back
    to a small built-in list, so the script works even without the
    downloaded data).
  - Draws a base literacy rate from the real indicator values in
    raw_downloads/ (if available) and applies a small random variation,
    simulating a new measurement.

Each event is a JSON object with fields like `municipality_id`, `year`,
`literacy_percentage`, published to Kinesis via the route
`infrastructure/create_stream.sh` -> stream -> Lambda -> S3 Bronze
(`s3://<bronze>/streaming/`).

--dry-run mode: since Kinesis charges per shard-hour even without traffic,
--dry-run doesn't call the Kinesis API, but writes the events directly to S3
Bronze in the same format (JSON Lines) that the Lambda would produce -- this
lets you validate the pipeline's final result without having to create the
stream. The files are marked with the "dry-run-" filename prefix so they
don't get confused with files generated by the Lambda from a real Kinesis
stream.

Usage:
  python pipelines/streaming/producer.py                     # 20 events, 1 batch
  python pipelines/streaming/producer.py --count 50 --batch-size 10 --interval 2
  python pipelines/streaming/producer.py --dry-run           # writes to S3 without using Kinesis
"""
from __future__ import annotations

import argparse
import gzip
import json
import random
import sys
import time
import uuid
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))  # enables `import common`
from common import (  # noqa: E402
    BRONZE_BUCKET,
    KINESIS_STREAM_NAME,
    get_kinesis_client,
    get_logger,
    get_s3_client,
)

logger = get_logger("producer")

KINESIS_PUT_RECORDS_LIMIT = 500  # PutRecords API limit per call
STREAMING_PREFIX = "streaming"  # same prefix used by lambda_consumer.py

# Fallback municipality (municipality_id, state_code), used when
# raw_downloads/ is not available -- keeps the script self-sufficient for
# demo purposes.
FALLBACK_MUNICIPALITIES: tuple[tuple[str, str], ...] = (
    ("3550308", "SP"),  # Sao Paulo
    ("3304557", "RJ"),  # Rio de Janeiro
    ("3106200", "MG"),  # Belo Horizonte
    ("2927408", "BA"),  # Salvador
    ("2304400", "CE"),  # Fortaleza
    ("5300108", "DF"),  # Brasilia
    ("4106902", "PR"),  # Curitiba
    ("4314902", "RS"),  # Porto Alegre
    ("1302603", "AM"),  # Manaus
    ("2611606", "PE"),  # Recife
)
FALLBACK_RATE_RANGE = (40.0, 95.0)


@dataclass(frozen=True)
class Municipality:
    municipality_id: str
    state_code: str


def _open_any(path: Path):
    return gzip.open(path, "rt", encoding="utf-8") if path.suffix == ".gz" else open(
        path, "r", encoding="utf-8"
    )


def load_municipalities(raw_downloads_dir: Path) -> list[Municipality]:
    """Reads municipality_id + state_code from raw_downloads/, if the file exists."""
    import csv

    for pattern in ("municipios.csv*", "br_bd_diretorios_brasil_municipio.csv*"):
        matches = sorted(raw_downloads_dir.glob(pattern))
        if not matches:
            continue
        path = matches[0]
        try:
            with _open_any(path) as fh:
                reader = csv.DictReader(fh)
                municipalities = [
                    Municipality(row["id_municipio"], row["sigla_uf"])
                    for row in reader
                    if row.get("id_municipio") and row.get("sigla_uf")
                ]
            if municipalities:
                logger.info("%d real municipalities loaded from %s", len(municipalities), path.name)
                return municipalities
        except Exception:
            logger.warning("Failed to read municipalities from %s, using fallback", path.name)
    logger.warning(
        "No municipalities CSV found in %s -- using %d fallback municipalities",
        raw_downloads_dir,
        len(FALLBACK_MUNICIPALITIES),
    )
    return [Municipality(*m) for m in FALLBACK_MUNICIPALITIES]


def load_base_rates(raw_downloads_dir: Path) -> list[float]:
    """Reads real literacy rates from raw_downloads/ to use as a realistic
    base for the synthetic variations. If not found, uses a default range."""
    import csv

    for pattern in (
        "indicador_crianca_alfabetizada.csv*",
        "br_inep_avaliacao_alfabetizacao_municipio.csv*",
    ):
        matches = sorted(raw_downloads_dir.glob(pattern))
        if not matches:
            continue
        path = matches[0]
        try:
            with _open_any(path) as fh:
                reader = csv.DictReader(fh)
                rates = [
                    float(row["taxa_alfabetizacao"])
                    for row in reader
                    if row.get("taxa_alfabetizacao")
                ]
            if rates:
                logger.info("%d real rates loaded from %s to use as a base", len(rates), path.name)
                return rates
        except Exception:
            logger.warning("Failed to read rates from %s, using default range", path.name)
    logger.warning(
        "No indicator CSV found in %s -- using default range %s",
        raw_downloads_dir,
        FALLBACK_RATE_RANGE,
    )
    return []


def make_event(municipality: Municipality, year: int, base_rates: list[float], rng: random.Random) -> dict:
    base = rng.choice(base_rates) if base_rates else rng.uniform(*FALLBACK_RATE_RANGE)
    variation = rng.uniform(-2.0, 2.0)
    percentage = round(min(100.0, max(0.0, base + variation)), 2)

    return {
        "event_id": str(uuid.uuid4()),
        "municipality_id": municipality.municipality_id,
        "state_code": municipality.state_code,
        "year": year,
        "literacy_percentage": percentage,
        "source": "simulated-streaming",
        "event_timestamp": datetime.now(timezone.utc).isoformat(),
    }


def send_batch(kinesis_client, stream_name: str, events: list[dict]) -> tuple[int, int]:
    """Publishes a batch of events via PutRecords. Returns (succeeded, failed)."""
    records = [
        {"Data": json.dumps(event).encode("utf-8"), "PartitionKey": event["municipality_id"]}
        for event in events
    ]
    response = kinesis_client.put_records(StreamName=stream_name, Records=records)
    failed = response.get("FailedRecordCount", 0)
    if failed:
        logger.warning("%d/%d records failed to publish to the stream", failed, len(events))
    return len(events) - failed, failed


def write_batch_to_s3(s3_client, bucket: str, prefix: str, events: list[dict]) -> str:
    """Writes a batch of events directly to S3 Bronze, in the same JSON Lines
    format the Lambda would produce from a real Kinesis stream. Used by
    --dry-run to validate the final pipeline result without needing the
    stream."""
    body = "\n".join(json.dumps(event, ensure_ascii=False) for event in events)
    dt = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    key = f"{prefix}/dt={dt}/dry-run-{uuid.uuid4()}.json"
    s3_client.put_object(Bucket=bucket, Key=key, Body=body.encode("utf-8"))
    return key


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--count", type=int, default=20, help="Total number of events to generate (default: 20)")
    parser.add_argument(
        "--batch-size",
        type=int,
        default=20,
        help=f"Events per PutRecords call, max {KINESIS_PUT_RECORDS_LIMIT} (default: 20)",
    )
    parser.add_argument(
        "--interval",
        type=float,
        default=1.0,
        help="Seconds to wait between batches, simulating near-real-time arrival (default: 1.0)",
    )
    parser.add_argument(
        "--year", type=int, default=datetime.now().year + 1, help="Simulated year for the events (default: current year + 1)"
    )
    parser.add_argument(
        "--stream", default=KINESIS_STREAM_NAME, help=f"Kinesis stream name (default: {KINESIS_STREAM_NAME})"
    )
    parser.add_argument(
        "--bucket", default=BRONZE_BUCKET, help=f"Bronze S3 bucket, used in --dry-run (default: {BRONZE_BUCKET})"
    )
    parser.add_argument(
        "--streaming-prefix",
        default=STREAMING_PREFIX,
        help=f"Prefix inside the Bronze bucket, used in --dry-run (default: {STREAMING_PREFIX})",
    )
    parser.add_argument(
        "--raw-downloads-dir",
        default="raw_downloads",
        help="Folder with the real CSVs used as a base (default: raw_downloads)",
    )
    parser.add_argument("--seed", type=int, default=None, help="Random generator seed (for reproducible runs)")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Writes the events directly to S3 Bronze (JSON, same format as the Lambda), without publishing to Kinesis",
    )
    args = parser.parse_args()

    if args.batch_size > KINESIS_PUT_RECORDS_LIMIT:
        logger.error("--batch-size cannot exceed %d (PutRecords API limit)", KINESIS_PUT_RECORDS_LIMIT)
        return 1

    rng = random.Random(args.seed)
    raw_downloads_dir = Path(args.raw_downloads_dir)
    municipalities = load_municipalities(raw_downloads_dir)
    base_rates = load_base_rates(raw_downloads_dir)

    kinesis_client = None if args.dry_run else get_kinesis_client()
    s3_client = get_s3_client() if args.dry_run else None
    if args.dry_run:
        logger.info(
            "--dry-run mode: events will NOT be published to Kinesis, but will be written "
            "directly to s3://%s/%s/ (same format as the Lambda)",
            args.bucket,
            args.streaming_prefix,
        )
    else:
        logger.info("Publishing events to stream '%s'", args.stream)

    sent, failed = 0, 0
    remaining = args.count
    while remaining > 0:
        batch_count = min(args.batch_size, remaining)
        events = [make_event(rng.choice(municipalities), args.year, base_rates, rng) for _ in range(batch_count)]

        if args.dry_run:
            key = write_batch_to_s3(s3_client, args.bucket, args.streaming_prefix, events)
            sent += len(events)
            logger.info("  [OK] %d event(s) written to s3://%s/%s", len(events), args.bucket, key)
        else:
            ok, err = send_batch(kinesis_client, args.stream, events)
            sent += ok
            failed += err
            logger.info("  [OK] batch published: %d event(s) (%d failed)", ok, err)

        remaining -= batch_count
        if remaining > 0 and args.interval > 0:
            time.sleep(args.interval)

    logger.info("Done: %d event(s) published, %d failure(s)", sent, failed)
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
